---
# Build wheel packages

- name: Check if the wheel package of {{ package }} is already built
  stat: path=/vagrant/build/{{ package|replace("-", "_") }}-{{ version }}-{{ py_tag }}-{{ abi_tag }}-linux_x86_64.whl
  register: wheel

- name: Build wheel package for {{ package }}
  command: "{{ pip }} wheel {{ package }}=={{ version }} --wheel-dir /vagrant/build"
  when: not wheel.stat.exists
